### ISSUE TITLE
I did

### ISSUE THREAD

**Issue by JeltzProstetnic** [Arminius-Software/face2video#8]
right after install.py:

Traceback (most recent call last):
  File "C:\_AI\deforum2\webui\extensions\face2video\main.py", line 3, in <module>
    import copy_sound_from_video
  File "C:\_AI\deforum2\webui\extensions\face2video\copy_sound_from_video.py", line 1, in <module>
    from moviepy.editor import VideoFileClip
ModuleNotFoundError: No module named 'moviepy'

However, moviepy was successfully installed. What is going on here? Can you help me?

**Comment by Arminius-Software** [comment]
Hi, it looks like you installed face2video inside some kind of extension folder. It would probably be best not to mix this up with other scripts/environments.

I think this is most likely due to some other conflicting installs if you installed the libraries into your global Python environment.
If that is the case, then using a virtual environment for the program should fix your issue. You can do that with a few simple commands (run in cmd with the path to the files of face2video. assuming your are using Windows):

"python -m venv venv"
"venv\Scripts\activate"
"python install.py"
"python main.py"

Let me know if using a clean new environment does not fix your problem.

**Comment by jakyet** [comment]
hello ,
firstly I would like like to thank you for your amazing Software .
everything was working perfectly until i updated the extentions of stable Diffusion and reactor was of them , since then the Software splits the frames and swap them but i can't see anything in the finished Frames file ,  the ReActor gets an error everytime while saving the result .
I tried deleting and reinstalling but the issue still remains .
what do you think is the issue here and can you help me fix it ?

**Comment by Arminius-Software** [comment]
@jakyet 
Hi, could you let me know the version of Reactor you have installed and whether you are using Automatic 1111 or Forge UI (Forge no longer receives updates, so installing newer versions of extensions will likely break things)? Can you also confirm that Reactor itself still works during a simple img2img?

**Comment by jakyet** [comment]
Stable diffusion v 1.8.0
Automatic 1111 
Reactor v 0.7.1-a1 
simple img2img Reactor works fine .
All processes of  face2video seem to function fine as well , the swapping process time is as usual and the GPU working only error is saving the output frames ( ReActor - Error while saving result : JPG  )

**Comment by Arminius-Software** [comment]
@jakyet I am currently very busy with university. I will try to reproduce/fix your issue at the beginning of August and then get back to you.

**Comment by jakyet** [comment]
All good , I solved the problem:
I reverted back to ReActor v 0.7.0 and it works fine now.
Nevertheless , thanks for your help and good luck with Uni 👍

**Comment by Arminius-Software** [comment]
@jakyet I had time to check the issue, and it should be solved in the newest version now. Reactor's newest version did not want to save images as JPG but only as PNG. Let me know if you still have any issues.
